// Typed API client with transparent sample fallback.
//
// Phase 11 renders from a committed sample snapshot (generated by the real
// pipeline — see backend/data/export_frontend_sample.py) because the live
// insight endpoints land in Phase 12. When the backend serves
// /api/meta | /api/timeseries | /api/insights?persona=, this client picks
// them up automatically with no frontend changes. /telemetry is live
// today (Phase 10) and falls back to the sample snapshot if the backend
// is unreachable.

import sampleMeta from "../data/sample/meta.json";
import sampleTimeseries from "../data/sample/timeseries.json";
import sampleCfo from "../data/sample/insights_cfo.json";
import sampleCm from "../data/sample/insights_category_manager.json";
import sampleTelemetry from "../data/sample/telemetry.json";

const SAMPLE_INSIGHTS = {
  CFO: sampleCfo,
  "Category Manager": sampleCm,
};

async function tryLive(path) {
  const res = await fetch(path, { headers: { Accept: "application/json" } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  if (typeof data !== "object" || data === null) throw new Error("malformed payload");
  return data;
}

export async function loadMeta() {
  try {
    return { data: await tryLive("/api/meta"), live: true };
  } catch {
    return { data: sampleMeta, live: false };
  }
}

export async function loadTimeseries() {
  try {
    return { data: await tryLive("/api/timeseries"), live: true };
  } catch {
    return { data: sampleTimeseries, live: false };
  }
}

export async function loadInsights(persona) {
  try {
    const data = await tryLive(`/api/insights?persona=${encodeURIComponent(persona)}`);
    if (!Array.isArray(data.insights)) throw new Error("malformed insights payload");
    return { data, live: true };
  } catch {
    return { data: SAMPLE_INSIGHTS[persona] ?? sampleCfo, live: false };
  }
}

// Phase 12: feedback. POST returns the recorded vote + updated feedback
// block; on success the caller re-fetches the feed (the server rebuild is
// pure re-ranking — zero extra LLM calls).
export async function postFeedback({ insight_id, persona, rating }) {
  const res = await fetch("/api/feedback", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ insight_id, persona, rating }),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data.detail || `HTTP ${res.status}`);
    err.detail = data.detail;
    throw err;
  }
  return data;
}

export async function loadFeedbackSummary(persona) {
  try {
    const data = await tryLive(
      `/api/feedback/summary${persona ? `?persona=${encodeURIComponent(persona)}` : ""}`
    );
    return { data, live: true };
  } catch {
    return { data: null, live: false };
  }
}

export async function loadTelemetry() {
  try {
    const data = await tryLive("/telemetry");
    if (!data || typeof data !== "object" || !data.llm) throw new Error("malformed telemetry");
    // A fresh server instance has an empty collector (no stages, 0 calls).
    // Rather than show an empty panel, fall back to the sample snapshot —
    // a real recorded instrumented run — and the UI labels it as such.
    const hasActivity =
      Object.keys(data.stages || {}).length > 0 || (data.llm?.calls ?? 0) > 0;
    return { data: hasActivity ? data : sampleTelemetry, live: hasActivity };
  } catch {
    return { data: sampleTelemetry, live: false };
  }
}
