"""
Frontend Sample Data Exporter — Phase 11 (shared service since Phase 12)
==========================================================================

Generates the sample data snapshot the Phase 11 dashboard renders when the
backend is unreachable. Runs the REAL deterministic pipeline (detection →
reconciliation → decomposition → confidence → actions, instrumented by
Phase 10) plus clearly-labeled MOCK narration per persona, applies Phase 6
access control (Category Manager never receives Gross Margin % — those
insights are recorded as blocked decisions instead), and writes:

    frontend/src/data/sample/meta.json
    frontend/src/data/sample/timeseries.json
    frontend/src/data/sample/insights_cfo.json
    frontend/src/data/sample/insights_category_manager.json
    frontend/src/data/sample/telemetry.json

Since Phase 12 the feed construction lives in `api/insights_service.py`
(also used by the live endpoints), so this exporter and the API share ONE
code path — the sample can never drift from what the API serves.

Every number in the output is pipeline-derived — nothing is invented here.
Narration text is mock (LLM_MOCK_MODE forced) and carries the [MOCK] label
+ mock: true flags, so the UI can never present it as a real LLM output.

Usage (from backend/ with the venv active):
    python data/export_frontend_sample.py
"""

import json
import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))      # backend/data
BACKEND_DIR = os.path.dirname(BASE_DIR)                    # backend
ROOT_DIR = os.path.dirname(BACKEND_DIR)
sys.path.insert(0, BACKEND_DIR)
os.environ["LLM_MOCK_MODE"] = "true"  # sample data must never call a real LLM

import pandas as pd

from contracts.loader import ContractStore
from engine.telemetry import TelemetryCollector, instrument_pipeline
from api.insights_service import build_insights, build_timeseries

RAW_DIR = os.path.join(BASE_DIR, "raw")
OUT_DIR = os.path.join(ROOT_DIR, "frontend", "src", "data", "sample")
PERSONAS = ["CFO", "Category Manager"]


def _load():
    sales = pd.read_csv(os.path.join(RAW_DIR, "sales_transactions.csv"), parse_dates=["date"])
    marketing = pd.read_csv(os.path.join(RAW_DIR, "marketing_spend.csv"))
    roster = pd.read_csv(os.path.join(RAW_DIR, "customer_roster.csv"))
    return sales, marketing, roster


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    sales, marketing, roster = _load()
    store = ContractStore()

    collector = TelemetryCollector()
    result = instrument_pipeline(collector, sales, marketing, roster, store)

    # --- meta ---
    meta = {
        "generated_at": pd.Timestamp.now("UTC").isoformat(),
        "window": {
            "start": str(sales["date"].min())[:10],
            "end": str(sales["date"].max())[:10],
        },
        "personas": PERSONAS,
        "source_freshness": result["reconciliation"].source_freshness,
        "sample": True,
        "note": (
            "Sample snapshot generated by the deterministic pipeline with "
            "mock narration (clearly labeled). Phase 12 serves this data live."
        ),
    }

    # --- per-persona insight feeds (shared service; mock narration fills telemetry) ---
    feeds = {}
    for p in PERSONAS:
        feed = build_insights(p, result, collector, feedback_store=None)
        feed["sample"] = True
        feed["source"] = "sample-pipeline-snapshot (Phase 12 serves this live)"
        feeds[p] = feed

    # --- telemetry snapshot from this very run ---
    telemetry = collector.snapshot()

    def _write(name: str, obj) -> None:
        path = os.path.join(OUT_DIR, name)
        with open(path, "w") as f:
            json.dump(obj, f, indent=2, default=str)
        print(f"  wrote {path} ({os.path.getsize(path):,} bytes)")

    print(f"Pipeline: {result['total_ms']} ms "
          f"({len(result['detection'].anomalies)} anomalies, "
          f"{len(result['confidence'].results)} confidence results, "
          f"{result['actions'].total_recommendations} recommendations)")
    _write("meta.json", meta)
    _write("timeseries.json", build_timeseries(sales, roster, result))
    for p in PERSONAS:
        _write(f"insights_{p.lower().replace(' ', '_')}.json", feeds[p])
    _write("telemetry.json", telemetry)

    for p in PERSONAS:
        f = feeds[p]
        print(f"{p}: {len(f['insights'])} insights, "
              f"{len(f['blocked'])} blocked KPI(s) {sorted(f['blocked'])}")
    print("✅ Frontend sample data exported")


if __name__ == "__main__":
    main()
